### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by gohsan53** [gohsan53/freemarket_sample_70_a_#2]
■URL
IPアドレス　http://54.199.47.20/
Github　https://github.com/gohsan53/freemarket_sample_70_a_

■Basic認証
ID: freemarket_sample70a
Pass: 0601

■テスト用アカウント
○購入者用
メールアドレス: testuser2@gmail.com
パスワード: testuser

○購入用カード情報
番号：4242424242424242
期限：12/20
セキュリティコード：123

○出品者用
メールアドレス名: testuser3@gmail.com
パスワード: testuser

**Comment by iwataayumu** [comment]
70期Aチームフリマアプリですが、
今朝、確認しまして、LGTMとさせていただいてます。
おめでとうございます！

スクラムマスターよりフォークの完了後は
個人での提出は大丈夫です！
